-- select ROUTER, COMPONENT from SYS_JMS_RESOURCE;

-- select DISTINCT ROUTER from SYS_JMS_RESOURCE;
-- select DISTINCT COMPONENT from SYS_JMS_RESOURCE;
select ROUTER , COMPONENT from SYS_JMS_RESOURCE where ROUTER is not NULL and COMPONENT is not NULL ;
